# Extend the default gitleaks rules.
#
# Add specific allowlists (paths, regexes, or stopwords) for false positives.
# These can include test secrets, fixtures, or documentation examples.
# There are no known false positives.
[extend]
useDefault = true
